typography_spectrum: 0.51085
color:
  brandColors:
    - '#121510'
    - '#efeff7'
    - '#74686a'
    - '#b7b2c5'
    - '#365c91'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.56141
analytics:
  google: UA-80328576-1
  facebook: null
  twitter: null
author:
  name: Neb Nosam
  email: nebwise@gmail.com
  url: nebcinema.com
name: neb.Cinema
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: neb.Cinema
purpose: []
