layout_spectrum: 0.6054533903952688
typography_spectrum: 0.20234716613776982
color:
  brandColors:
    - '#D8D9DA'
    - '#FF8B39'
    - '#222C42'
    - '#787589'
    - '#AA9C7E'
  brandStrength: 0.47940643737092614
  lightness: 0.6491175510454923
  saturation: 0.5651115213986486
  rhythmicContrast: 0.09840954258106649
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-80328576-1
  facebook: null
  twitter: null
author:
  name: Neb Nosam
  email: nebwise@gmail.com
  url: nebcinema.com
name: neb.Cinema
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: neb.Cinema
purpose: []
