name: neb.Cinema
favicon: null
layout_spectrum: 0.58773
typography_spectrum: 0.51085
title: neb.Cinema
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121510'
    - '#efeff7'
    - '#74686a'
    - '#b7b2c5'
    - '#365c91'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
